# Generated by Django 5.1.2 on 2024-10-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatments_name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis_app.diagnosis')),
            ],
        ),
    ]
