# Generated by Django 5.1.2 on 2024-10-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=300)),
                ('diagnosis_at', models.DateTimeField(auto_now_add=True)),
                ('Patients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_app.patients')),
            ],
        ),
    ]
