# Generated by Django 5.1.2 on 2024-10-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=300)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('userprofile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.userprofile')),
            ],
        ),
    ]
